//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.7905
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.CompactFramework.Design.Data, Version 2.0.50727.7905.
// 
namespace Framework.Service.Provider.WebService.Provider {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSFacadeServiceSoapBinding", Namespace="http://webservice.coms.gss.com/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(PartnerInfo))]
    public partial class WSFacadeService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public WSFacadeService() {
            this.Url = "http://localhost:8080/BargeOperation/ws/";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservice.coms.gss.com/execute", RequestNamespace="http://webservice.coms.gss.com/", ResponseNamespace="http://webservice.coms.gss.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("responseInfo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public ResponseInfo execute([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)] RequestInfo request) {
            object[] results = this.Invoke("execute", new object[] {
                        request});
            return ((ResponseInfo)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Beginexecute(RequestInfo request, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("execute", new object[] {
                        request}, callback, asyncState);
        }
        
        /// <remarks/>
        public ResponseInfo Endexecute(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ResponseInfo)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.coms.gss.com/")]
    public partial class RequestInfo {
        
        private string methodNameField;
        
        private string serviceIDField;
        
        private object[] parmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string methodName {
            get {
                return this.methodNameField;
            }
            set {
                this.methodNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string serviceID {
            get {
                return this.serviceIDField;
            }
            set {
                this.serviceIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("parm", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public object[] parm {
            get {
                return this.parmField;
            }
            set {
                this.parmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.coms.gss.com/")]
    public partial class ResponseInfo {
        
        private object[] resultObjField;
        
        private object tempItemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("resultObj", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public object[] resultObj {
            get {
                return this.resultObjField;
            }
            set {
                this.resultObjField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public object tempItem {
            get {
                return this.tempItemField;
            }
            set {
                this.tempItemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://webservice.coms.gss.com/")]
    public partial class PartnerInfo {
        
        private string codeField;
        
        private string nameField;
        
        private string createdDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string createdDate {
            get {
                return this.createdDateField;
            }
            set {
                this.createdDateField = value;
            }
        }
    }
}
